### ISSUE TITLE
Errors came up when running ApplyOfflineMap in Tempest-Remap

### ISSUE THREAD

**Issue by Burniezz** [jweyn/DLWP-CS#1]
Hi, buddies, 
I’m trying to reimplement your cube-sphere unet which is the leading benchmark in WatherBench so far, however, some error occurred when I took the ApplyOfflineMap procedure in Tempest-Remap. 
My input file is hourly geopotential height data which has a variable ‘z’ from WeatherBench, and my test.py file is like:

``` python

import os
os.chdir(os.pardir)
from DLWP.remap import CubeSphereRemap

data_directory = '/home/rlu/DLWP-CS'
processed_file = '%s/geopotential_500hPa_2018_5.625deg.nc' % data_directory
remapped_file = '%s/geo500_cube.nc' % data_directory

csr = CubeSphereRemap(path_to_remapper='/home/rlu/bin', verbose=True)

csr.generate_offline_maps(lat=32, lon=64, res=48, inverse_lat=True, remove_meshes=False)
csr.remap(processed_file, '%s/temp.nc' % data_directory, '--var', 'z')
csr.convert_to_faces('%s/temp.nc' % data_directory,
                     remapped_file,
                     coord_file=processed_file,
                     chunking={'sample': 1, 'varlev': 1})

os.remove('%s/temp.nc' % data_directory)

```

Seems I worked through these procedure: ./GenerateRLLMesh, ./GenerateCSMesh, ./GenerateOverlapMesh, ./GenerateOfflineMap, the trace is like:

``` txt

CubeSphereRemap: generating offline forward map...
/home/rlu/bin/GenerateRLLMesh --lat 32 --lon 64 --file outLL.g --lat_begin 90 --lat_end -90 --out_format Netcdf4
/home/rlu/bin/GenerateCSMesh --res 48 --file outCS.g --out_format Netcdf4
/home/rlu/bin/GenerateOverlapMesh --a outLL.g --b outCS.g --out ov_LL_CS.g --out_format Netcdf4
/home/rlu/bin/GenerateOfflineMap --in_mesh outLL.g --out_mesh outCS.g --ov_mesh ov_LL_CS.g --in_np 1 --in_type FV --out_type FV --out_map map_LL32x64_CS48.nc --out_format Netcdf4
CubeSphereRemap: generating offline inverse map...
/home/rlu/bin/GenerateOverlapMesh --a outCS.g --b outLL.g --out ov_CS_LL.g --out_format Netcdf4
/home/rlu/bin/GenerateOfflineMap --in_mesh outCS.g --out_mesh outLL.g --ov_mesh ov_CS_LL.g --in_np 1 --in_type FV --out_type FV --out_map map_CS48_LL32x64.nc --out_format Netcdf4
CubeSphereRemap: successfully generated offline maps (map_LL32x64_CS48.nc, map_CS48_LL32x64.nc)

```

But after that an error occurred while applying the offline map which is like:

```txt

CubeSphereRemap: applying forward map...
/home/rlu/bin/ApplyOfflineMap --in_data /home/rlu/DLWP-CS/geopotential_500hPa_2018_5.625deg.nc --out_data /home/rlu/DLWP-CS/temp.nc --map map_LL32x64_CS48.nc --var z
An error occurred while applying the offline map.
b'Parameters:\n  --in_data <string> ["/home/rlu/DLWP-CS/geopotential_500hPa_2018_5.625deg.nc"] \n  --in_data_list <string> [""] \n  --map <string> ["map_LL32x64_CS48.nc"] \n  --var <string> ["z"] \n  --out_data <string> ["/home/rlu/DLWP-CS/temp.nc"] \n  --out_data_list <string> [""] \n  --ncol_name <string> ["ncol"] \n  --out_double <bool> [false] \n  --preserve <string> [""] \n  --preserveall <bool> [false] \n  --fillvalue <double> [0.000000] \n  --logdir <string> [""] \n------------------------------------------------------------\nLoading offline map.. Done\nProcessing "/home/rlu/DLWP-CS/geopotential_500hPa_2018_5.625deg.nc"\n..z'
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    csr.remap(processed_file, '%s/temp.nc' % data_directory, '--var', 'z')
  File "/home/rlu/DLWP-CS/DLWP/remap/cubesphere.py", line 348, in remap
    subprocess.check_output(cmd)
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/rlu/bin/ApplyOfflineMap', '--in_data', '/home/rlu/DLWP-CS/geopotential_500hPa_2018_5.625deg.nc', '--out_data', '/home/rlu/DLWP-CS/temp.nc', '--map', 'map_LL32x64_CS48.nc', '--var', 'z']' died with <Signals.SIGSEGV: 11>.

```

To solve this unexpected problem, I tested the script on two Linux machines but came into the same trouble. I doubt that the Tempest-Remap package is problematic when the input is from WeatherBench, so could you help me work this problem out?

Thanks.

Ren

**Comment by jweyn** [comment]
Hi Ren, looks like you encountered one of tempest-remap's unfortunately frequent random segmentation fault errors. Most often when I've gotten these errors I have been able to work around them by generating a new netCDF data file that has all unnecessary coordinates and attributes removed.

Now, I just downloaded the geopotential_500 data and tried it out myself, and it worked correctly for me. I had to dig into the tempest-remap source code to find the version but mine is from Feb 14, 2020 (technically 2.0.2 but it looks like a recent commit on that GitHub repo was made just to change the version number to 2.0.5). If you just retrieved the tempest-remap package from conda-forge though, it should be recent. Here are two ideas to try:

- See if generating maps by reading the file works: `csr.generate_offline_maps_from_file(processed_file, res=48)`. This will say whether you have a recent enough version of the package. It's better to do this anyway because it will do a better job of mapping where the grid points are.
- Try removing the `level` coordinate (tempest-remap does not usually tolerate `int` types at all):
```
ds = xr.open_dataset(processed_file)
ds.load().drop('level').to_netcdf(new_file)
```

Feel free to update if these don't work.

**Comment by Burniezz** [comment]
Thanks @jweyn , simply removing '''txt time ''' coordinate in netCDF files will work.

**Comment by Burniezz** [comment]
Thanks @jweyn , simply removing time and level coordinates in netCDF files will work.

**Comment by jweyn** [comment]
Yep, it's too bad the package is so finicky. Glad you got it to work @Burniezz.
