### ISSUE TITLE
Error downloading ERA5 data

### ISSUE THREAD

**Issue by priya-sharma-07** [jweyn/DLWP-CS#2]

**Comment by priya-sharma-07** [comment]
hello jweyn,

I am getting following error while running file 1 - Downloading and processing ERA5.ipynb
![erro1](https://user-images.githubusercontent.com/65880337/91293652-f8f31b00-e7b5-11ea-92d3-2e6684553a5c.png)
![error2](https://user-images.githubusercontent.com/65880337/91293659-fabcde80-e7b5-11ea-9d42-744f40e3500d.png)
![error3](https://user-images.githubusercontent.com/65880337/91293667-fbee0b80-e7b5-11ea-813e-39fceaef266b.png)
![error4](https://user-images.githubusercontent.com/65880337/91293670-fc86a200-e7b5-11ea-9529-e51986c1ffe8.png)





can you please help me resolving this issue.
i am attaching the file screenshots here.

**Comment by jweyn** [comment]
Hi @priya-sharma-07, try changing In[15] to have `years = list(range(2013, 2015))` instead. Python range objects take a start, end (not inclusive), step. So this would include years 2013 and 2014.

**Comment by priya-sharma-07** [comment]
Thanks for your reply @jweyn.
 I changed the years. But again i am getting same error. Can you please go through the screenshot once again? 
Because the error the i am getting as (your request is not valid). I am exactly running the same code that provided in tutorial folder in DLWP-CS folder.

**Comment by jweyn** [comment]
Ok then I'd need to go test it out myself. I'll see if I can find time to try it. But I'm a little concerned it may be a Windows-specific issue (I have not tried it on Windows).

**Comment by priya-sharma-07** [comment]
I tried the same code on linux machine also. That is also showing the same
error. if you get some time then please check it out.

**Comment by jweyn** [comment]
I just ran everything successfully on my install. I added an [environment.yml](https://github.com/jweyn/DLWP-CS/blob/master/environment.yml) file so you can compare python packages (`conda env export > environment.yml`). Otherwise the only thing I could also recommend trying is setting `levels = [500]`.

**Comment by priya-sharma-07** [comment]
thank you so much @jweyn for your reply. I resolved that error by using environment.yml. Actually, there were some missing packages that's why I was facing that error. Thanks once again. I will let you if  I face any problem regarding this code.
