### ISSUE TITLE
CNN input layer dimension

### ISSUE THREAD

**Issue by Priya-Sharma07** [jweyn/DLWP-CS#4]
Hello @jweyn could you please tell me why you considered exactly 48 points on each side of the cube faces, which
corresponds to roughly 1.9-degree grid spacing in latitude and longitude in the center of the equatorial faces. what 48 indicates here?. it will be very helpful to understand 
![ask1](https://user-images.githubusercontent.com/42205160/95605376-7d53e180-0a76-11eb-8d5f-956ce68227df.PNG)
CNN  architecture.

**Comment by jweyn** [comment]
Hi @miniproject2018, sorry for the delay. The choice was fairly arbitrary, it seemed like a good balance of atmospheric resolution and data processing requirements to start there. Most recently we have been working with 64-point cubed sphere faces, about 1.4 degrees.

**Comment by priya-sharma-07** [comment]
okay, thank u.

**Comment by Priya-Sharma07** [comment]
okay, thank u.
