### ISSUE TITLE
convolution_shape in ArrayDataGenerator class

### ISSUE THREAD

**Issue by manmeet3591** [jweyn/DLWP-CS#5]
I am trying to modify DLWP-CS for a case wherein I don't have recurrent data. There is some error that is coming in creating the model due to a shape mismatch. The error is appended below. In the tutorial notebook I checked the generator.convolution_shape and it prints (6, 48, 48, 6). What is the first 6 representing? When I checked one the comment for convolution shape in the class it says

the shape of the predictors expected by a Conv2D or ConvLSTM2D layer. If the model is recurrent,
 (time_step, channels, y, x); if not, (channels, y, x). Includes insolation.

I am providing the shape as (1,6,512,512) and 'channels_first' argument.

@jweyn Can you please help me resolve this issue ?

-----------------------------------------------------------------------------------------------------------------------------------
ValueErrorTraceback (most recent call last)
<ipython-input-96-02cc62c77145> in <module>
     19 
     20 from tensorflow.keras.models import Model
---> 21 model = Model(inputs=main_input, outputs=unet2(main_input))

<ipython-input-93-b24055172a1f> in unet2(x)
     16     x2 = up_sampling_2(x2)
     17     x = concatenate([x2, x1], axis=-1)
---> 18     x = cube_padding_1(x)
     19     x = relu(conv_2d_6_2(x))
     20     x = cube_padding_1(x)

~/manmeet/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
    924     if _in_functional_construction_mode(self, inputs, args, kwargs, input_list):
    925       return self._functional_construction_call(inputs, args, kwargs,
--> 926                                                 input_list)
    927 
    928     # Maintains info about the `Layer.call` stack.

~/manmeet/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py in _functional_construction_call(self, inputs, args, kwargs, input_list)
   1115           try:
   1116             with ops.enable_auto_cast_variables(self._compute_dtype_object):
-> 1117               outputs = call_fn(cast_inputs, *args, **kwargs)
   1118 
   1119           except errors.OperatorNotAllowedInGraphError as e:

~/manmeet/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py in wrapper(*args, **kwargs)
    256       except Exception as e:  # pylint:disable=broad-except
    257         if hasattr(e, 'ag_error_metadata'):
--> 258           raise e.ag_error_metadata.to_exception(e)
    259         else:
    260           raise

ValueError: in user code:

    /lus/dal/cccr_rnd/manmeet/AI_IITM/WeatherBench/notebooks/DLWP/custom.py:1099 call  *
        out.append(K.expand_dims(
    /lus/dal/cccr_rnd/manmeet/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py:201 wrapper  **
        return target(*args, **kwargs)
    /lus/dal/cccr_rnd/manmeet/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/backend.py:2881 concatenate
        return array_ops.concat([to_dense(x) for x in tensors], axis)
    /lus/dal/cccr_rnd/manmeet/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /lus/dal/cccr_rnd/manmeet/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py:1654 concat
        return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
    /lus/dal/cccr_rnd/manmeet/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py:1222 concat_v2
        "ConcatV2", values=values, axis=axis, name=name)
    /lus/dal/cccr_rnd/manmeet/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:744 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    /lus/dal/cccr_rnd/manmeet/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py:593 _create_op_internal
        compute_device)
    /lus/dal/cccr_rnd/manmeet/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:3485 _create_op_internal
        op_def=op_def)
    /lus/dal/cccr_rnd/manmeet/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:1975 __init__
        control_input_ops, op_def)
    /lus/dal/cccr_rnd/manmeet/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:1815 _create_c_op
        raise ValueError(str(e))

    ValueError: Dimension 0 in both shapes must be equal, but are 512 and 256. Shapes are [512] and [256]. for '{{node cube_sphere_padding2d_5/concat_171}} = ConcatV2[N=3, T=DT_FLOAT, Tidx=DT_INT32](cube_sphere_padding2d_5/transpose_98, cube_sphere_padding2d_5/strided_slice_442, cube_sphere_padding2d_5/transpose_99, cube_sphere_padding2d_5/concat_171/axis)' with input shapes: [?,64,1,256], [?,64,256,512], [?,64,1,256], [] and with computed input tensors: input[3] = <2>.

**Comment by manmeet3591** [comment]
@jweyn

**Comment by manmeet3591** [comment]
I was able to resolve it. I was giving the wrong shape as (1,6,512,512). It should be (6,512,512,1) and the program works. So basically I was able to understand the way padding is done and channels are at the last. Thank you.

**Comment by jweyn** [comment]
Apologies for not getting to this in a timely manner. I'm glad you were able to figure out the problem.
